# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Only publish to AzDO NPM when a tag is pushed to master.
# NOTE: a PR needs to be opened from dev --> master, which includes version bump.
# If needs be, we can eventually automate.
trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - core/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- checkout: self
  clean: true
  persistCredentials: true
  fetchDepth: 1

- task: Bash@3
  name: BumpNpmVersion
  displayName: Bump NPM Prerelease Version
  inputs:
    targetType: filePath
    filePath: ./scripts/version.sh
    arguments: '@multicloud/sls-core'
    workingDirectory: core
  env:
    SOURCE_BRANCH: $(Build.SourceBranch)

- task: Npm@1
  inputs:
    command: publish --tag=beta --access public
    workingDir: core
    publishEndpoint: NPM
    verbose: true
